Entities/DataContext.cs
using System;
using Microsoft.EntityFrameworkCore;
namespace EXAMP.Entities
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions options) : base(options)
        {

        }

        public DbSet<Department> Departments { get; set; }
        public DbSet<Staff> Staffs { get; set; }
    }
}

Entities/Department.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EXAMP.Entities
{
    [Table("departments")]

    public class Department
    {
        [Key]
        public int id { get; set; }

        [Required]
        public string name { get; set; }

        public ICollection<Staff> staffs { get; set; }
    }
}

Entities/Staff.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EXAMP.Entities
{
    [Table("staffs")]

    public class Staff
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(200)]
        public string name { get; set; }
        [Required]
        public int age { get; set; }
        [Required]
        public string email { get; set; }
        public int department_id { get; set; }
        [ForeignKey("department_id")]
        public Department Department { get; set; }
    }
}

Models/DepartmentEditModel.cs
using System.ComponentModel.DataAnnotations;

namespace EXAMP.Models
{
    public class DepartmentEditModel
    {
        [Required]
        public int id { get; set; }

        [Required(ErrorMessage = "Vui Lòng nhập tên danh mục")]
        [MinLength(6, ErrorMessage = "Vui lòng nhập tối thiếu 6 kí tự")]
        [Display(Name = "Tên danh mục")]
        public string name { get; set; }
    }
}

Models/DepartmentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace EXAMP.Models
{
    public class DepartmentViewModel
    {
        [Required(ErrorMessage = "Vui Lòng nhập tên danh mục")]
        [MinLength(6, ErrorMessage = "Vui lòng nhập tối thiếu 6 kí tự")]
        [Display(Name = "Tên danh mục")]
        public string name { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace EXAMP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/StaffViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EXAMP.Models
{
    public class StaffViewModel
    {
        [Required]
        public string name { get; set; }
        [Required]
        public int age { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        [Display(Name = "Department")]
        public int department_id { get; set; }
    }
}

Controllers/DepartmentController.cs
using EXAMP.Entities;
using EXAMP.Models;
using Microsoft.AspNetCore.Mvc;

namespace EXAMP.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly DataContext _context;
        public DepartmentController(DataContext context)
        {
            _context = context;
        }

        //Get: /<Controller>/
        public IActionResult Index()
        {
            var departments = _context.Departments.ToList();
            ViewBag.departments = departments;
            return View(departments);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DepartmentViewModel model)
        {
            if (ModelState.IsValid) // validate
            {
                _context.Departments.Add(new Department { name = model.name });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Department department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(new DepartmentEditModel { id = department.id, name = department.name });
        }

        [HttpPost]
        public IActionResult Edit(DepartmentEditModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Departments.Update(new Department
                {
                    id = model.id,
                    name = model.name
                });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            Department department = _context.Departments.Find(id);
            if (department == null)
            {
                return NotFound();
            }
            _context.Departments.Remove(department);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using EXAMP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EXAMP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StaffController.cs
using EXAMP.Entities;
using EXAMP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;


namespace EXAMP.Controllers
{
    public class StaffController : Controller
    {
        private readonly DataContext _context;
        public StaffController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Staff> staffs = _context.Staffs.Include(p => p.department_id).ToList();

            return View(staffs);
        }

        public IActionResult List()
        {
            return View();
        }

        public IActionResult Create()
        {
            List<Department> departments = _context.Departments.ToList();
            var selectDepartments = new List<SelectListItem>();
            foreach (var c in departments)
            {
                selectDepartments.Add(new SelectListItem { Text = c.name, Value = c.id.ToString() });
            }
           

            ViewBag.departments = selectDepartments;
            return View();
        }

        [HttpPost]
        public IActionResult Create(StaffViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Staffs.Add(new Staff
                {
                    name = model.name,
                    age = model.age,
                    email = model.email,
                    department_id = model.department_id,
                });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            List<Department> departments = _context.Departments.ToList();
            var selectDepartments = new List<SelectListItem>();
            foreach (var c in departments)
            {
                selectDepartments.Add(new SelectListItem { Text = c.name, Value = c.id.ToString() });
            }


           
            ViewBag.departments = selectDepartments;

            return View();
        }
    }
}

Views/Department/Create.cshtml
@model EXAMP.Models.DepartmentViewModel
@{
}
@using (Html.BeginForm(FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h1 class="text-center">Create Department</h1>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
                @using (Html.BeginForm("Create", "Department", FormMethod.Post))
                {
                    <div class="mb-3">
                        @Html.LabelFor(m => m.name)
                        @Html.TextBoxFor(m => m.name, new {@class="form-control"})
                        @Html.ValidationMessageFor(m => m.name,"", new {@class="text-danger"})

                    </div>

                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                }
            </div>
            <div class="col"></div>
        </div>
    </div>
}

Views/Department/Edit.cshtml
@model EXAMP.Models.DepartmentEditModel
@{
}
<h1 class="text-center">Edit Department:@Model.name</h1>
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            @using (Html.BeginForm("Edit", "Department", FormMethod.Post))
            {
                @Html.HiddenFor(m=>m.id)
                <div class="mb-3">
                    @Html.LabelFor(m => m.name)
                    @Html.TextBoxFor(m => m.name, new {@class="form-control"})
                    @Html.ValidationMessageFor(m => m.name,"", new {@class="text-danger"})
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            }
            <div class="mb-3">
                @Html.ActionLink("Back to list","Index")
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>

Views/Department/Index.cshtml
@model List<EXAMP.Entities.Department>
@{
    
}
<H1>Department Page</H1>
<a asp-controller="Category" asp-action="Create" class="btn btn-primary"> Create new Department</a>
<div class="col-6">
    <table class="table">
        <thead>
        <th>ID</th>
        <th>Name</th>
        <th></th>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.id</td>
                    <td>@item.name</td>
                    <td>

                        <a href="@Url.ActionLink("Edit","Department",new{id=item.id})"
                           class="btn btn-primary">Edit</a>
                    </td>

                    <td>

                        <a href="@Url.ActionLink("Delete","Department",new{id=item.id})"
                           onclick="return confirm('Bạn muốn xóa danh mục @item.name')"
                           class="btn btn-primary">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EXAMP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EXAMP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EXAMP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EXAMP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Staff/Create.cshtml
@model EXAMP.Models.StaffViewModel
@{
}
<h1 class="text-center">Create Staff</h1>
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            @using (Html.BeginForm("Create", "Staff", FormMethod.Post))
            {
                <div class="mb-3">
                    @Html.LabelFor(m => m.name)
                    @Html.TextBoxFor(m => m.name, new {@class="form-control"})
                    @Html.ValidationMessageFor(m => m.name,"", new {@class="text-danger"})
                </div>
                <div class="mb-3">
                    @Html.LabelFor(m => m.age)
                    @Html.TextBoxFor(m => m.age, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.age, "", new { @class = "text-danger" })
                </div>
                <div class="mb-3">
                    @Html.LabelFor(m => m.email)
                    @Html.TextBoxFor(m => m.email, new {@class="form-control"})
                    @Html.ValidationMessageFor(m => m.email,"", new {@class="text-danger"})
                </div>
                <div class="mb-3">
                    @Html.LabelFor(m => m.department_id)
                    @Html.DropDownListFor(m => m.department_id,(IEnumerable<SelectListItem>)ViewBag.categories, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.department_id, "", new { @class = "text-danger" })
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            }
        </div>
        <div class="col"></div>
    </div>
</div>

Views/Staff/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Staff/Index.cshtml
@model List<EXAMP.Entities.Product>
@{

}
<H1>Product Page</H1>
<a asp-controller="Product" asp-action="Create" class="btn btn-primary"> Create new Product</a>
<div class="col-6">
    <table class="table">
        <thead>
        <th>ID</th>
        <th>Name</th>
        <th>age</th>
        <th>email</th>
        <th>Department</th>
        <th></th>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.id</td>
                    <td>@item.name</td>
                    <td>@item.age</td>
                    <td>@item.email</td>
                    <td>@item.department</td>

                    <td>

                        <a href="@Url.ActionLink("Edit","Staff",new{id=item.id})"
                           class="btn btn-primary">Edit</a>
                    </td>

                    <td>

                        <a href="@Url.ActionLink("Delete","Staff",new{id=item.id})"
                           onclick="return confirm('Bạn muốn xóa sản phẩm @item.name')"
                           class="btn btn-primary">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>